name: "Image Builder"


on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the Docker image"
        required: true
        type: string
        default: "latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Replace version placeholder in Dockerfile
        run: | 
          VERSION=${{ github.event.inputs.version }}
          echo "Replacing placeholder with version: $VERSION"
          sed -i "s/VERSION_PLACEHOLDER/$VERSION/" devops/html/index.html 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.event.inputs.version }} -f devops/Dockerfile .
      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.event.inputs.version }}

  trigger-update-tag:
    needs: build-and-push
    uses: ./.github/workflows/reusable-template.yaml
    with:
      #file_path: "manifests/apps/entity/base/deployment.yaml"
      file_path: "manifests/apps/entity/overlays/dev/deployment-patch.yaml"
      pr_title: "Bump version to ${{ github.event.inputs.version }}"
      pr_body: "Automated update of application version."
      branch_name: "update-tag-${{ github.event.inputs.version }}"
      updated_version: "${{ github.event.inputs.version }}"
      channel_id: "C08BAR4AXCH"
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
