name: "Image Builder"

on:
  workflow_dispatch:
  push: 
    branches: ["main"]
    paths:
      - "devops/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.TAG }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Tag Number
        id: set_tag
        run: |
          VERSION="version-${{ github.run_number }}"
          echo "TAG=$VERSION" >> $GITHUB_ENV
          echo "TAG=$VERSION" >> $GITHUB_OUTPUT  # Save output

      - name: Replace version placeholder in index.html
        run: |
          echo "Replacing placeholder with version: $TAG"
          sed -i "s/VERSION_PLACEHOLDER/$TAG/" devops/html/index.html

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          echo "Building image with tag: $TAG"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:"$TAG" -f devops/Dockerfile .

      - name: Push the Docker image to Docker Hub
        run: |
          echo "Pushing image with tag: $TAG"
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:"$TAG"

  trigger-update-tag:
    needs: build-and-push
    uses: ./.github/workflows/reusable-template.yaml
    with:
      file_path: "manifests/apps/entity/overlays/dev/deployment-patch.yaml"
      pr_title: "Bump version to ${{ needs.build-and-push.outputs.image_tag }}"
      pr_body: "Automated update of application version."
      branch_name: "update-tag-${{ needs.build-and-push.outputs.image_tag }}"
      updated_version: "nginx:${{ needs.build-and-push.outputs.image_tag }}"
      channel_id: "C08BAR4AXCH"
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
