name: "Image Builder"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the Docker image"
        required: true
        type: string
        default: "latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Replace version placeholder in Dockerfile
        run: | 
          VERSION=${{ github.event.inputs.version }}
          echo "Replacing placeholder with version: $VERSION"
          sed -i "s/VERSION_PLACEHOLDER/$VERSION/" devops/html/index.html 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.event.inputs.version }} -f devops/Dockerfile .
      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.event.inputs.version }}

  trigger-update-tag:
    needs: build-and-push
    uses: ./.github/workflows/reusable-template.yaml
    with:
      file_path: "manifests/apps/entity/base/deployment.yaml"
      search_pattern: "image: nginx:latest"
      replace_value: "image: nginx:${{ github.event.inputs.version }}"
      pr_title: "Bump version to ${{ github.event.inputs.version }}"
      pr_body: "Automated update of application version."
      branch_name: "update-tag-${{ github.event.inputs.version }}"
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  slack-notification:
    needs: trigger-update-tag
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
	  method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
	  payload: |
	    channel: 'C08BAR4AXCH'
	    text: "A new PR has been created for 'entity service' version bump to ${{ github.event.inputs.version }}. Please review."
