name: "Update Tag and Create PR"

on:
  workflow_call:
    inputs:
      file_path:
        required: true
        type: string
      updated_version:
        required: true
        type: string
        default: "latest"
      pr_title:
        required: false
        type: string
        default: "Update tag version"
      pr_body:
        required: false
        type: string
        default: "Automated PR to update the tag version"
      branch_name:
        required: false
        type: string
        default: "update-tag"
      text:
        required: true
        type: string
        default: "Hi!"

    secrets:
      SLACK_BOT_TOKEN:
        required: true
      GH_TOKEN:
        required: true

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: 'devops-contribution/k8s-apps'
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: list
        run: ls

      - name: Update Version in File
        run: |
          yq -i '.spec.template.spec.containers[0].image = "nginx:${{ inputs.updated_version }}"' "${{ inputs.file_path }}"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Branch and Commit Changes
        run: |
          git checkout -b "${{ inputs.branch_name }}"
          git add "${{ inputs.file_path }}"
          git commit -m "chore: update tag version to '${{ inputs.updated_version }}'"
          git pull --rebase
          git push origin "${{ inputs.branch_name }}"

      - name: Check File
        run: cat "${{ inputs.file_path }}"

      - name: Debug Git History
        run: git log --oneline -5

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: "${{ inputs.branch_name }}"
          base: main
          title: "${{ inputs.pr_title }}"
          commit-message: "${{ inputs.pr_body }}"

  slack-notification:
    needs: update-tag
    runs-on: ubuntu-latest
    steps:
      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "C08BAR4AXCH"
            text: "${{ inputs.text }}"
