name: Update Tag and Create PR
on:
  workflow_call:
    inputs:
      file_path:
        required: true
        type: string
      updated_version:
        required: true
        type: string
        default: latest
      pr_title:
        required: false
        type: string
        default: Update tag version
      pr_body:
        required: false
        type: string
        default: Automated PR to update the tag version
      branch_name:
        required: false
        type: string
        default: update-tag
      channel_id:
        required: true
        type: string
        default: ""
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      GH_PAT:
        required: true
jobs:
  update-tag:
    runs-on: ubuntu-latest
    outputs:
      pr_url: ${{ steps.cpr.outputs.pull-request-url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: devops-contribution/k8s-apps
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Update Version in File
        run: |
          yq -i '.spec.template.spec.containers[0].image = "docker.io/muk007/nginx:${{inputs.updated_version }}"' "${{ inputs.file_path }}"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          branch: ${{ inputs.branch_name }}
          base: "main"
          title: ${{ inputs.pr_title }}
          body: ${{ inputs.pr_body }}
          labels: automated, update, entity service
          reviewers: 'devops-contribution'

  slack-notification:
    needs: update-tag
    runs-on: ubuntu-latest
    steps:
      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "${{ inputs.channel_id }}"
            text: "🚀 A new PR has been created, pls review: ${{ needs.update-tag.outputs.pr_url }}"
