name: "Update AUTHORS"

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: devops-contribution/k8s-apps
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update AUTHORS
        run: |
          echo "test" > ./text.txt
          BRANCH_NAME="update-authors-$(date +%s)"  # Unique branch name
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "UPDATE"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/devops-contribution/k8s-apps.git
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: update authors
          base: "main"
          title: Update AUTHORS
          body: Credit new contributors by updating AUTHORS
          branch: $BRANCH_NAME  # Use the dynamically generated branch name
