name: "Update AUTHORS"

on:
  workflow_dispatch:

jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: devops-contribution/k8s-apps
          fetch-depth: 0
     
      - name: List
        run: ls

      - name: Update AUTHORS
        run: |
          echo "test" > k8s-apps/text.txt
          git checkout -b update-authors
          git add .
          git commit -m "UPDATE"
          git push origin update-authors

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: update authors
          title: Update AUTHORS
          body: Credit new contributors by updating AUTHORS
          branch: update-authors
