name: "Image Builder"


on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the Docker image"
        required: true
        type: string
        default: "latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Print variable
        run: echo ${{ github.event.inputs.version }}
